vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        media_object:
            uri_prefix: /media
            upload_destination: '%kernel.project_dir%/public/media'
            # Will rename upladed files usng a uniqueid as a prefix.
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer